### ISSUE TITLE
When a cheat day is live you cannot add challenges to it.

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#109]
1)Day 2 is a cheat day - live
2) Add a challenge and assign it to day 2 - beginner.
3) there should be a message saying that day 2 is a live cheat day and cannot add to it.

Incase the cheat day is in draft status, then there should be a pop up informing the user that the day.
Message: "Day 2 for Beginner level is a cheat day but in draft status". Do you still want to add the challenge to this day? 
Proceed + Cancel actions

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35549131-fed3498c-05a9-11e8-85c8-028b7058c492.png)
