### ISSUE TITLE
When the challenge is in draft status, there should not be an option to archive the challenge

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#116]
![image](https://user-images.githubusercontent.com/19943710/35222585-69e0e4c0-ffa4-11e7-8571-088529a02f6b.png)

**Comment by SavantMaithili** [comment]
Issue persists:
![image](https://user-images.githubusercontent.com/35555935/35316704-0d75a012-00f9-11e8-8aee-4cf80c977e47.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35318436-60802fcc-0101-11e8-8e7b-fb374a369f3d.png)
