### ISSUE TITLE
If additional details are not added for a diet challenge which is published, on edit do not show the additional details section

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#117]
![image](https://user-images.githubusercontent.com/19943710/35222792-0ece7b0a-ffa5-11e7-84d0-6ac496b845b4.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35320180-eda22386-0108-11e8-8b30-c3d796ff9e6b.png)
