### ISSUE TITLE
Based on the number of slides, it should be named as Slide 1, Slide 2 and so on

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#118]
![image](https://user-images.githubusercontent.com/19943710/35222881-70d5a2b0-ffa5-11e7-8e96-2edd926f25d9.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35332599-8884deac-0131-11e8-9ae4-45b083e16a4a.png)
