### ISSUE TITLE
Wrong message is displayed when trying to mark day 1 as cheat

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#119]
![image](https://user-images.githubusercontent.com/19943710/35222951-caa8567a-ffa5-11e7-8cf3-36bcb49bca69.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35499682-72d25082-04f9-11e8-8f2e-d6113666ad8b.png)
