### ISSUE TITLE
Double click on "Add Day" action results in the addition of 2 days 

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#120]
![image](https://user-images.githubusercontent.com/19943710/35223377-317269c6-ffa7-11e7-904a-591e9c3f3269.png)

**Comment by SavantMaithili** [comment]
Duplicate of "Add Day - 2 consequent days at a time #105", fixed, tested, closed.

**Comment by SavantMaithili** [comment]
Observed again , Reopened #105 
![image](https://user-images.githubusercontent.com/35555935/35263918-b7b42bd4-0040-11e8-8c58-20cead18d30d.png)
