### ISSUE TITLE
Wrong message is displayed when the user tries to uncheck the "mark as cheat day flag"

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#121]
![image](https://user-images.githubusercontent.com/19943710/35223495-9318229c-ffa7-11e7-8bfa-aae17526e2bf.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35272090-12c44734-005a-11e8-8cee-4234c0d41f6d.png)
