### ISSUE TITLE
When the admin archives a challenge on a particular day and if the challenge is present on the other days too a warning message should be displayed to the user before archiving it.

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#123]
![image](https://user-images.githubusercontent.com/19943710/35258505-046c20c8-0026-11e8-8867-4b9d129e649c.png)

![image](https://user-images.githubusercontent.com/19943710/35258507-0ad4db12-0026-11e8-926a-1ac226314c54.png)

The message should be "This challenge is also present on *day(s)*. Archiving the challenge will archive it from all days, Please confirm if you want to proceed"

Actions : Proceed & Cancel

**Comment by tanvisalkar** [comment]
as dicussed shows the error message "This challenge is also present on day(s) hence cannot be archived!!" with no popup for confirmation.

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35315459-841764c8-00f2-11e8-9fb6-b91ae6112194.png)
![image](https://user-images.githubusercontent.com/35555935/35315481-971a524c-00f2-11e8-8d25-6f2ac3475e3f.png)
![image](https://user-images.githubusercontent.com/35555935/35315506-b3c1b23c-00f2-11e8-8e43-3b63b297d111.png)
This message should be displayed only if the challenge to be archived is **the only published challenge** (fitness or diet) present in any of the Live days, reason being there should be at-least 1 fitness and diet challenge in published state to be live

ELSE

The message should be "This challenge is also present on day(s). Archiving the challenge will archive it from all days, Please confirm if you want to proceed"

Actions : Proceed & Cancel

**Comment by SavantMaithili** [comment]
See below scenario:
![image](https://user-images.githubusercontent.com/35555935/35327088-a593b940-011e-11e8-9763-a6788c226118.png)
"C00091 | 1 (Published) " is available as published on both the days.. Archiving this on Day 8 should not be allowed as this is the only published challenge for day 9 which is LIVE.
![image](https://user-images.githubusercontent.com/35555935/35327198-05a9419c-011f-11e8-9a69-cedd78656e4c.png)
![image](https://user-images.githubusercontent.com/35555935/35327215-1147cd48-011f-11e8-9710-b505581fa4e2.png)

**Comment by SavantMaithili** [comment]
Also, header message should be changed as this pop up is to change challenge status
![image](https://user-images.githubusercontent.com/35555935/35327501-b8a52522-011f-11e8-8aca-f279858e79be.png)

**Comment by SavantMaithili** [comment]
Scenario 1 : Works!
![image](https://user-images.githubusercontent.com/35555935/35329995-dbeff37e-0127-11e8-8f9a-3a66662e5557.png)
![image](https://user-images.githubusercontent.com/35555935/35330003-ebb3bd18-0127-11e8-807e-bbb42865e07b.png)
**Scenario 2: Text Error**
![image](https://user-images.githubusercontent.com/35555935/35330035-01502d8c-0128-11e8-9bb7-a8cc2c9635eb.png)
![image](https://user-images.githubusercontent.com/35555935/35330357-490a7154-0129-11e8-9c71-18ea2a1d5086.png)
Scenario 3: Works!
![image](https://user-images.githubusercontent.com/35555935/35330557-eddc380c-0129-11e8-81a9-e1a34ce7ccb4.png)
![image](https://user-images.githubusercontent.com/35555935/35330566-0005a748-012a-11e8-9729-2c30b9240caa.png)
****Scenario 4:** - Pop Up Text Error**
![image](https://user-images.githubusercontent.com/35555935/35330693-63d8e33e-012a-11e8-8a9d-1c4ce89be3c2.png)

**Comment by SavantMaithili** [comment]
Needs the fix on **acknowledgement  pop up** as well, pleas see bleo:
![image](https://user-images.githubusercontent.com/35555935/35497261-6d5d6b32-04ef-11e8-933f-e9cc9b5d8a8a.png)
Works in below message
![image](https://user-images.githubusercontent.com/35555935/35497329-bbecc6bc-04ef-11e8-916b-9fb8a9971175.png)

**Comment by SavantMaithili** [comment]
Works now
![image](https://user-images.githubusercontent.com/35555935/35498612-08de78e4-04f5-11e8-8854-1a3becd0cb0f.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35550170-4115895e-05af-11e8-89b4-a8c9531f64f2.png)

**Comment by SavantMaithili** [comment]
Day 1 has more than 1 published challenge and is **Live**. 
Day 2 is in **Draft** and contains one challenge from Day 1. -
User **should** be able to archive the common one in both these days as this is not the only published challenge in Live Day
Day 1 - Archive AD1 - Should allow as this day is Live and this is not the only challenge in Day 1, Day 2 is draft
Day 2 - Archive AD1 - Should allow as this day is draft and this is not the only challenge in Day 1 that is Live
![image](https://user-images.githubusercontent.com/35555935/35607776-fa3a3d40-067b-11e8-81c1-53835b388bc5.png)

**Comment by SavantMaithili** [comment]
Tracking all archive issues in #140, closing this
