### ISSUE TITLE
For basecamp, on saving the basecamp instead of description the message is displayed.

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#124]
![image](https://user-images.githubusercontent.com/19943710/35258896-7b74065c-0028-11e8-8545-43801bf5d74e.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35270708-f5c63a7e-0055-11e8-96cd-9cdec0fe5670.png)
![image](https://user-images.githubusercontent.com/35555935/35270742-0230ac54-0056-11e8-8db8-11da6ae85d2d.png)
