### ISSUE TITLE
On the configuration of basecamp page, the "Message" should be renamed and also the place holder

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#125]
![image](https://user-images.githubusercontent.com/19943710/35258923-bdc83df2-0028-11e8-995f-6c359b892544.png)

1) Message - Success Message
2) Type a message for the user - Type a message for the user on successful completion of basecamp

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35270869-5e70b0f4-0056-11e8-9735-1819eac81613.png)
