### ISSUE TITLE
On the list of challenges table, under column type if a particular filter is selected, then the subtype filter values should be based on the type filter chosen

### ISSUE THREAD

**Issue by Valenie** [ajency/Healthwise#126]
![image](https://user-images.githubusercontent.com/19943710/35259865-2491c026-002e-11e8-94c6-9b5534366068.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35495785-a4d4c8f0-04e8-11e8-9a2a-b53d93913b2e.png)
![image](https://user-images.githubusercontent.com/35555935/35495796-b47029d0-04e8-11e8-8627-312f496c748f.png)
