### ISSUE TITLE
Alignment issue - Level tables - List of challenges added to any day

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/Healthwise#127]
![image](https://user-images.githubusercontent.com/35555935/35260343-0604cf1a-0031-11e8-8f60-76204306fb0c.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35260619-83310a84-0032-11e8-9d72-7b65f154190a.png)

**Comment by tanvisalkar** [comment]
@SavantMaithili the aligment changes as per the size of the content by default the text is justified (horizontically centered).. Also the text is dynamic.

**Comment by SavantMaithili** [comment]
Closing as per above comments
