### ISSUE TITLE
'Clone' functionality missing in Actions - List of Challenges

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/Healthwise#129]
![image](https://user-images.githubusercontent.com/35555935/35263058-3309081c-003d-11e8-84da-1fbf3727648e.png)
![image](https://user-images.githubusercontent.com/35555935/35263086-582cabf8-003d-11e8-8826-3ce1ad8f36b4.png)

**Comment by sharangsamonkar** [comment]
this functionality is on hold for now.
