### ISSUE TITLE
error message is displayed saying "Cheat challenge already exists." when type selected is cheat while adding a challenge 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/Healthwise#20]
http://healthwise.ajency.in/dashboard/challenge/add

1. add challenge
2. select type as cheat 
3. fill all the required fields 
4. create

current : error message displayed saying cheat challenge already exists
![image](https://user-images.githubusercontent.com/17116943/34521017-7d2c7c94-f0b1-11e7-8e1d-403429cb09f0.png)

**Comment by sharangsamonkar** [comment]
You can only add cheat challenge once.

**Comment by cinthiavernekar** [comment]
noted
