### ISSUE TITLE
uploaded featured image is not getting saved in below scenario

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/Healthwise#3]
http://healthwise.ajency.in/dashboard/challenge/add

1. go to add challenge 
2. fill all the required fields except **description** 
3. upload featured image -> save

current : validation message for description is thrown where uploaded featured image is not saved.

**Comment by sharangsamonkar** [comment]
Image doesn't get uploaded if there are errors in the form. No data is stored in case of any errors.

**Comment by cinthiavernekar** [comment]
noted
