### ISSUE TITLE
Please add an option to delete the exercise

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#45]
Add a delete exercise button on top right of each exercise.

Ask for confirmation while deleting. "You are about to delete an exercise. Are you sure ? " - Yes, No

![image](https://user-images.githubusercontent.com/26400070/34662102-37e9010e-f474-11e7-8d5a-9334c31526f0.png)

**Comment by sharangsamonkar** [comment]
Already working on it.

**Comment by SumithraKB** [comment]
Need to add for diet as well

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35273515-dd2f576c-005e-11e8-86b1-5c6840117289.png)
Works for both FItness-Others & Diet-Others
