### ISSUE TITLE
Align check box with the text 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/Healthwise#6]
http://healthwise.ajency.in/dashboard/challenge/edit/C00004

![image](https://user-images.githubusercontent.com/17116943/34482418-e817176e-efdd-11e7-8911-cea2b2178da1.png)

**Comment by SumithraKB** [comment]
works now
![image](https://user-images.githubusercontent.com/26400070/34595525-baa319fe-f1fe-11e7-8cdd-fe578df743d9.png)
