### ISSUE TITLE
Issue with success message on grace period screen

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#65]
http://healthwise.ajency.in/dashboard/grace-period

Steps : 
1. Add some value to grace period and save.
![image](https://user-images.githubusercontent.com/26400070/34927413-f2c51032-f9db-11e7-8d52-402a42dca5a8.png)
2. Close the success message
3. Change the value and click on save.
Success message is not shown

![image](https://user-images.githubusercontent.com/26400070/34927434-283c9ed8-f9dc-11e7-8a11-8669387c1b66.png)

**Comment by SavantMaithili** [comment]
Works fine!
![image](https://user-images.githubusercontent.com/35555935/35206325-ebdbed6e-ff61-11e7-9226-47be6fd837fc.png)
![image](https://user-images.githubusercontent.com/35555935/35206368-33d3248e-ff62-11e7-83d6-1771f027d554.png)
