### ISSUE TITLE
Need cancel button on grace period screen

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#66]
Expected : 
![image](https://user-images.githubusercontent.com/26400070/34928840-4903cc9a-f9e6-11e7-82f2-3987e639da52.png)

Actual : 
![image](https://user-images.githubusercontent.com/26400070/34928835-39f6f146-f9e6-11e7-90d8-fa77326bc09c.png)

**Comment by SavantMaithili** [comment]
Cancel button added.
![image](https://user-images.githubusercontent.com/35555935/35206619-d0ebcc2a-ff63-11e7-9b09-bb4090b83c2e.png)
