### ISSUE TITLE
Show error message when user tries to save without adding grace period 

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#67]
Show error message when user tries to save without adding grace period. "Please enter grace period"

![image](https://user-images.githubusercontent.com/26400070/34930907-e75d4aaa-f9f1-11e7-8d27-43ab0c25dd00.png)

**Comment by SavantMaithili** [comment]
Validation message added.
![image](https://user-images.githubusercontent.com/35555935/35206537-4cf4cc64-ff63-11e7-927a-e8c4aac0f128.png)
