### ISSUE TITLE
Grace period is not immediately reflecting on point 2 and 3 , when increased/ decreased with the arrows

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#69]
Goto grace period screen and increase/decrease the grace period using up/down arrows

![image](https://user-images.githubusercontent.com/26400070/34976167-4850bd5a-fabb-11e7-85ef-9048e1768602.png)

![image](https://user-images.githubusercontent.com/26400070/34976195-67fae72a-fabb-11e7-987b-a78344109965.png)

**Comment by SavantMaithili** [comment]
Issue persists.
![image](https://user-images.githubusercontent.com/35555935/35206672-58d03bf8-ff64-11e7-880a-a2d8253318dc.png)
![image](https://user-images.githubusercontent.com/35555935/35206689-8666294c-ff64-11e7-973e-a3d3db6508f5.png)

**Comment by SavantMaithili** [comment]
Arrows missing
![image](https://user-images.githubusercontent.com/35555935/35259074-999cc19a-0029-11e8-8541-09a0946cf0ab.png)

**Comment by tanvisalkar** [comment]
@SavantMaithili  the initial field was numberfield so the arrows were showing but  the field is changed later to textfield to handle validations in order to allow only digits.... parsley validation

**Comment by SavantMaithili** [comment]
Closing as per above comments
