### ISSUE TITLE
Random code coming in add day screen

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#71]
Random code coming in add day screen,after making a day live
![image](https://user-images.githubusercontent.com/26400070/35039414-ca9c7e5a-fba3-11e7-96f0-4e4f071623d7.png)

**Comment by SavantMaithili** [comment]
No error.
![image](https://user-images.githubusercontent.com/35555935/35212925-d327333a-ff81-11e7-8f92-9bc6a5507ed1.png)
