### ISSUE TITLE
Able to mark a day live without adding any challenges

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#72]
![image](https://user-images.githubusercontent.com/26400070/35039513-1b3bf278-fba4-11e7-9ff5-55965024f1ab.png)

**Comment by SavantMaithili** [comment]
Validation added.
![image](https://user-images.githubusercontent.com/35555935/35210851-d3a19268-ff79-11e7-9070-c4d4ddef3880.png)
