### ISSUE TITLE
Add basecamp screen | Remove the text  "Basic Information" 

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#76]
![image](https://user-images.githubusercontent.com/26400070/35040101-f6437430-fba5-11e7-8e23-b9acb8c47285.png)

**Comment by SavantMaithili** [comment]
Label removed.
![image](https://user-images.githubusercontent.com/35555935/35211075-e520172a-ff7a-11e7-874f-5cb728cecbcf.png)
