### ISSUE TITLE
Basecamp which was added, is not shown in the add day screen

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#78]
Before adding basecamp : 

Beginner level : 
![image](https://user-images.githubusercontent.com/26400070/35040529-6b7858a0-fba7-11e7-8604-17031995092f.png)

Basecamp added after day 2 : 
![image](https://user-images.githubusercontent.com/26400070/35040597-ba47c330-fba7-11e7-866c-1e17ee3e69c3.png)

Basecamp is not shown in the table : 
![image](https://user-images.githubusercontent.com/26400070/35040616-cf90906e-fba7-11e7-8894-4d2b17c34eac.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35218259-fc1fb39a-ff93-11e7-8a0a-4b571d6800c0.png)
