### ISSUE TITLE
Additional details section dsnt change based upon the type + sub type combo selected 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/Healthwise#8]
http://healthwise.ajency.in/dashboard/challenge/edit/C00006

1. created a challenge with type fitness and subtype other 

current : additional details displayed are of type fitness and subtype walk
![image](https://user-images.githubusercontent.com/17116943/34482894-fd750726-efe0-11e7-950d-d24abfb17123.png)

Expected : for type fitness + other, additional details should be as below : 
https://drive.google.com/open?id=0B-KrjArGOLMraEk1U1dkUDF1NWVyMzN0ZExvSXRPNDYxTVRj

**Comment by sharangsamonkar** [comment]
@cinthiavernekar  this sprint includes only includes fitness + walk, fitness + cheat, diet + cheat

**Comment by cinthiavernekar** [comment]
noted
