### ISSUE TITLE
Able to add multiple basecamps after same day

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#80]
Steps.
1. Go to http://healthwise.ajency.in/dashboard/levels/beginner
2.Click on add basecamp
3. Add base campe after day 2
![image](https://user-images.githubusercontent.com/26400070/35040849-b404c896-fba8-11e7-913d-6c71959bad84.png)

Repeat this 
![image](https://user-images.githubusercontent.com/26400070/35040871-c97a5eca-fba8-11e7-98b2-f35427c6fffd.png)

![image](https://user-images.githubusercontent.com/26400070/35040918-eadeab2a-fba8-11e7-9fee-2387bc935065.png)

Expected : Should not be allowed to add multiple basecamps after same day

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35220454-78c35476-ff9c-11e7-9d35-d392aa9737ac.png)

![image](https://user-images.githubusercontent.com/35555935/35220435-61d3ead2-ff9c-11e7-9880-e978e84ca568.png)
