### ISSUE TITLE
Show a message to user while trying to mark a day live without published diet and fitness challenge

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#82]
While trying to mark a day live which do not have a published fitness and diet challenge. It should show a message to user to indicate that it needs one published diet and fitness challenge  and keep the day as draft itself

![image](https://user-images.githubusercontent.com/26400070/35081687-8eab5b80-fc3b-11e7-9dd0-3ad0934eeb31.png)

"Please add atleast one published Fitness and Diet challenges to mark this day as live"

![image](https://user-images.githubusercontent.com/26400070/35081692-9c50bc4e-fc3b-11e7-9b92-129cf86bbdd1.png)

**Comment by tanvisalkar** [comment]
on toggle switch the popup for confirmation before marking day live is shown and only onclick of the button "Yes" in the popup it attempts to mark the day live... hence the message shows onclcik of the button.. 
current message: "Day cannot be made Live. Does not have enough challenges to make Live!!"

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35259233-9e0d33c6-002a-11e8-861d-d9c5847300d6.png)
![image](https://user-images.githubusercontent.com/35555935/35259311-21190c5e-002b-11e8-93d9-ad430009ff4c.png)
