### ISSUE TITLE
Getting error message while adding basecamp even though base camp does not exist

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#83]
Tried to add base camp after day 9
![image](https://user-images.githubusercontent.com/26400070/35084899-33ddf4ae-fc4c-11e7-85d6-5a5614049919.png)

Gives this error.
![image](https://user-images.githubusercontent.com/26400070/35084919-47e91c94-fc4c-11e7-9fd0-a4bd16538112.png)

Getting same error while tried with any other day as well

![image](https://user-images.githubusercontent.com/26400070/35084992-a325c8be-fc4c-11e7-915a-02f48affd92b.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35211417-521fe8c2-ff7c-11e7-89f7-625d22bd1c09.png)
![image](https://user-images.githubusercontent.com/35555935/35211427-57ca5b18-ff7c-11e7-9bef-7da212f2b6db.png)
![image](https://user-images.githubusercontent.com/35555935/35211439-6aa15f48-ff7c-11e7-9ff8-070267be49c1.png)
