### ISSUE TITLE
Once a day is live , need to check if the day has atleast one published fitness and diet challenge, while changing the status of challenge

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#84]
Once a day is live , need to check if the day has atleast one published fitness and diet challenge, while changing the status of challenge

Currently, it allows to change the status to draft and there is only one published challenge added

Day 9- Live day with one published diet and fitness challenge each
![image](https://user-images.githubusercontent.com/26400070/35085945-bcc5f22c-fc50-11e7-9c5d-def8aca9d34d.png)
Able to change the status of these challenge to draft

![image](https://user-images.githubusercontent.com/26400070/35085999-f24c31d6-fc50-11e7-842f-a5ea50919da3.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35259585-b11c5616-002c-11e8-8fe8-cbbf2fa663dc.png) - FIxed!
Able to change the status of these challenge to draft - FIxed !
