### ISSUE TITLE
Spelling issue on grace period screen

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#86]
![image](https://user-images.githubusercontent.com/26400070/35140040-be5550c6-fd1b-11e7-8906-61cd907ff1a4.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35206242-527ac794-ff61-11e7-802c-ecd72160a600.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35210730-62859c50-ff79-11e7-9182-71d99826b2e6.png)
