### ISSUE TITLE
Keep position of "Day" drop down same of add and edit challenge screens

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#90]
Add challenge screen : 
![image](https://user-images.githubusercontent.com/26400070/35138227-8a022afe-fd13-11e7-8f10-cac2fb9ff104.png)

Edit challenge screen : 
![image](https://user-images.githubusercontent.com/26400070/35138257-c0cbb884-fd13-11e7-9780-b4c701cfecc8.png)

**Comment by SavantMaithili** [comment]
Edit:
![image](https://user-images.githubusercontent.com/35555935/35259484-3235e9b6-002c-11e8-8c7c-d4a30fe1489f.png)
Add:
![image](https://user-images.githubusercontent.com/35555935/35259493-3edc83c8-002c-11e8-95b6-c6e3c00379d0.png)
