### ISSUE TITLE
When challenge is present on multiple days, status change of challenge is not reflecting immediately on all days

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#91]
When challenge is present on multiple days, status change of challenge is not reflecting immediately on all days. After page refresh it works fine.

1. Add same challenge to multiple days. eg ; Added C00200 to day 6 and day 10.
2.  Change the status of challenge from Day 6, using the edit option against the challenge 

Change is reflected on Day 6, but not reflecting on Day 10
![image](https://user-images.githubusercontent.com/26400070/35138355-1f7a6a42-fd14-11e7-8bc8-907426715f95.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35220958-6047b570-ff9e-11e7-88f0-79b9588e292a.png)
![image](https://user-images.githubusercontent.com/35555935/35220992-817be7c0-ff9e-11e7-9c13-5c2bfe161f2a.png)
