### ISSUE TITLE
Move the day drop down beside level on add challenge screen

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#92]
http://healthwise.ajency.in/dashboard/challenge/add

![image](https://user-images.githubusercontent.com/26400070/35139901-1c73c9d6-fd1b-11e7-81df-6e13faad04d3.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35220605-0af59426-ff9d-11e7-815d-bc8d651be1bd.png)
