### ISSUE TITLE
Add challenge pop up , check boxes are not aligned properly

### ISSUE THREAD

**Issue by SumithraKB** [ajency/Healthwise#93]
Actual : 
![image](https://user-images.githubusercontent.com/26400070/35140125-1a28e566-fd1c-11e7-805a-4a993550df67.png)

Expected:
![image](https://user-images.githubusercontent.com/26400070/35140114-0d6dcd64-fd1c-11e7-8642-96dfdd26302a.png)

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35220273-b80b80e6-ff9b-11e7-844b-d3a05d3730b0.png)
